---

- include: facts.yml

- include: packages_redhat_{{ openstack_neutron_controller_neutron_plugin }}.yml
  when: ansible_os_family == 'RedHat'

- include: packages_debian_{{ openstack_neutron_controller_neutron_plugin }}.yml
  when: ansible_os_family == 'Debian'

- include: configuration_{{ openstack_neutron_controller_neutron_plugin }}.yml

- include: services.yml

- meta: flush_handlers

- include: sanitycheck.yml
