---

- name: Install Neutron midonet packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - neutron-server
    - python-networking-midonet
    - python-neutronclient

- name: Purge ML2 packages
  apt:
    name: '{{ item }}'
    state: absent
    purge: True
  with_items:
    - neutron-plugin-ml2
