---

- name: SANITY CHECK List networks
  shell: >-
    openstack
    --os-identity-api-version 3
    --os-auth-url {{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_port }}/v3
    --os-project-name '{{ demo_project }}'
    --os-username '{{ demo_user }}'
    --os-auth-type password
    --os-password '{{ demo_pass }}'
    --os-user-domain-id default
    --os-project-domain-id default
    network list
  register: network_list_test
  changed_when: network_list_test.rc != 0

- debug: var=network_list_test.stdout_lines
